/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/glbs/bar-stool.glb --output ./app/components/gltf/BarStool.tsx 
Author: Zhmyhers (https://sketchfab.com/zhmyhers)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bar-stool-e319d61521a64d1c91d77552ce5f5047
Title: Bar stool
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Seat_low_Material_#645_0']: THREE.Mesh
  }
  materials: {
    Material_645: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glbs/bar-stool.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['Seat_low_Material_#645_0'].geometry} material={materials.Material_645} position={[0, 22.147, 1.346]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/glbs/bar-stool.glb')
